ADMIT_WARD_HEADER = '入院病房(RYBF)'
ADMIT_TIME_HEADER = '入院时间(RYSJ)'


DISCHARGE_WARD_HEADER = '出院病房(CYBF)'
DISCHARGE_TIME_HEADER = '出院时间(CYSJ)'

# 出院诊断
PRIMARY_DIAGNOSIS_HEADER = '疾病编码（西医主要诊断）(XY_JBDM)'
PRIMARY_DIAGNOSIS_HEADER1 = '疾病编码（西医其他诊断1）(XY_JBDM1)'
PRIMARY_DIAGNOSIS_HEADER2 = '疾病编码（西医其他诊断2）(XY_JBDM2)'
PRIMARY_DIAGNOSIS_HEADER3 = '疾病编码（西医其他诊断3）(XY_JBDM3)'
PRIMARY_DIAGNOSIS_HEADER4 = '疾病编码（西医其他诊断4）(XY_JBDM4)'
PRIMARY_AGE_HEADER = '年龄(NL)'

# 1 好转
# 2 好转
# 4 好转
# 5 死亡
# 9 好转
DISCHARGE_METHOD_HEADER = '离院方式(LYFS)'

# 重症监护室名称
INTENSIVE_CARE_HEADER1 = '重症监护室名称1(ZZJHSMC1)'
INTENSIVE_CARE_HEADER2 = '重症监护室名称2(ZZJHSMC2)'
INTENSIVE_CARE_HEADER3 = '重症监护室名称3(ZZJHSMC3)'
INTENSIVE_CARE_HEADER4 = '重症监护室名称4(ZZJHSMC4)'
INTENSIVE_CARE_HEADER5 = '重症监护室名称5(ZZJHSMC5)'

# 入院诊断
ADMIT_DIAGNOSIS_HEADER1 = '入院诊断1(RYZD1)'
ADMIT_DIAGNOSIS_HEADER2 = '入院诊断2(RYZD2)'
ADMIT_DIAGNOSIS_HEADER3 = '入院诊断3(RYZD3)'
ADMIT_DIAGNOSIS_HEADER4 = '入院诊断4(RYZD4)'
ADMIT_DIAGNOSIS_HEADER5 = '入院诊断5(RYZD5)'

# '1' = 否
# '2' = 是
DISCHARGE_PLAN_HEADER_IN_31_DAYS_HEADER = '是否有出院31天内再出院计划(SFZZYJH)'

SURGERY_OPERATION_HEADER1 = '手术及操作编码1(SSBM1_S)'
SURGERY_OPERATION_HEADER2 = '手术及操作编码2(SSBM2_S)'
SURGERY_OPERATION_HEADER3 = '手术及操作编码3(SSBM3_S)'
SURGERY_OPERATION_HEADER4 = '手术及操作编码4(SSBM4_S)'
SURGERY_OPERATION_HEADER5 = '手术及操作编码5(SSBM5_S)'
SURGERY_OPERATION_HEADER6 = '手术及操作编码6(SSBM6_S)'
SURGERY_OPERATION_HEADER7 = '手术及操作编码7(SSBM7_S)'
SURGERY_OPERATION_HEADER8 = '手术及操作编码8(SSBM8_S)'
SURGERY_OPERATION_HEADER9 = '手术及操作编码9(SSBM9_S)'
SURGERY_OPERATION_HEADER10 = '手术及操作编码10(SSBM10_S)'


ACTUAL_INPATIENT_DAYS_HEADER = '实际住院天数(SJZYTS)'

DISCHARGE_STATUS_HEADER1 = '出院情况（西医其他诊断1）(XY_CYQK1)'
DISCHARGE_STATUS_HEADER2 = '出院情况（西医其他诊断2）(XY_CYQK2)'
DISCHARGE_STATUS_HEADER3 = '出院情况（西医其他诊断3）(XY_CYQK3)'
DISCHARGE_STATUS_HEADER4 = '出院情况（西医其他诊断4）(XY_CYQK4)'
DISCHARGE_STATUS_HEADER5 = '出院情况（西医其他诊断5）(XY_CYQK5)'
DISCHARGE_STATUS_HEADER6 = '出院情况（西医其他诊断6）(XY_CYQK6)'
DISCHARGE_STATUS_HEADER7 = '出院情况（西医其他诊断7）(XY_CYQK7)'
DISCHARGE_STATUS_HEADER8 = '出院情况（西医其他诊断8）(XY_CYQK8)'
DISCHARGE_STATUS_HEADER9 = '出院情况（西医其他诊断9）(XY_CYQK9)'
DISCHARGE_STATUS_HEADER10 = '出院情况（西医其他诊断10）(XY_CYQK10)'
DISCHARGE_STATUS_HEADER11 = '出院情况（西医其他诊断11）(XY_CYQK11)'
DISCHARGE_STATUS_HEADER12 = '出院情况（西医其他诊断12）(XY_CYQK12)'
DISCHARGE_STATUS_HEADER13 = '出院情况（西医其他诊断13）(XY_CYQK13)'
DISCHARGE_STATUS_HEADER14 = '出院情况（西医其他诊断14）(XY_CYQK14)'
DISCHARGE_STATUS_HEADER15 = '出院情况（西医其他诊断15）(XY_CYQK15)'
DISCHARGE_STATUS_HEADER16 = '出院情况（西医其他诊断16）(XY_CYQK16)'
DISCHARGE_STATUS_HEADER17 = '出院情况（西医其他诊断17）(XY_CYQK17)'
DISCHARGE_STATUS_HEADER18 = '出院情况（西医其他诊断18）(XY_CYQK18)'
DISCHARGE_STATUS_HEADER19 = '出院情况（西医其他诊断19）(XY_CYQK19)'
DISCHARGE_STATUS_HEADER20 = '出院情况（西医其他诊断20）(XY_CYQK20)'
