ADMIT_WARD_HEADER = '入院病房(RYBF)'
ADMIT_TIME_HEADER = '入院时间(RYSJ)'


DISCHARGE_WARD_HEADER = '出院病房(CYBF)'
DISCHARGE_TIME_HEADER = '出院时间(CYSJ)'

# 出院诊断
PRIMARY_DIAGNOSIS_HEADER = '疾病编码（西医主要诊断）(XY_JBDM)'
PRIMARY_DIAGNOSIS_HEADER1 = '疾病编码（西医其他诊断1）(XY_JBDM1)'
PRIMARY_DIAGNOSIS_HEADER2 = '疾病编码（西医其他诊断2）(XY_JBDM2)'
PRIMARY_DIAGNOSIS_HEADER3 = '疾病编码（西医其他诊断3）(XY_JBDM3)'
PRIMARY_DIAGNOSIS_HEADER4 = '疾病编码（西医其他诊断4）(XY_JBDM4)'
PRIMARY_AGE_HEADER = '年龄(NL)'

# 1 好转
# 2 好转
# 4 好转
# 5 死亡
# 9 好转
DISCHARGE_METHOD_HEADER = '离院方式(LYFS)'

# 重症监护室名称
INTENSIVE_CARE_HEADER1 = '重症监护室名称1(ZZJHSMC1)'
INTENSIVE_CARE_HEADER2 = '重症监护室名称2(ZZJHSMC2)'
INTENSIVE_CARE_HEADER3 = '重症监护室名称3(ZZJHSMC3)'
INTENSIVE_CARE_HEADER4 = '重症监护室名称4(ZZJHSMC4)'
INTENSIVE_CARE_HEADER5 = '重症监护室名称5(ZZJHSMC5)'

# 入院诊断
ADMIT_DIAGNOSIS_HEADER1 = '入院诊断1(RYZD1)'
ADMIT_DIAGNOSIS_HEADER2 = '入院诊断2(RYZD2)'
ADMIT_DIAGNOSIS_HEADER3 = '入院诊断3(RYZD3)'
ADMIT_DIAGNOSIS_HEADER4 = '入院诊断4(RYZD4)'
ADMIT_DIAGNOSIS_HEADER5 = '入院诊断5(RYZD5)'

# '1' = 否
# '2' = 是
DISCHARGE_PLAN_HEADER_IN_31_DAYS_HEADER = '是否有出院31天内再出院计划(SFZZYJH)'

SURGERY_OPERATION_HEADER = '手术及操作编码1(SSBM1_S)'
